services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=simple_bank
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@db:5432/simple_bank?sslmode=disable
    depends_on:
      db:
        condition: service_healthy